Repository openshift/knative-eventing-contrib, pull requests merged in 2019-06, with the labels that each got.

#59 Add kafka quay.io images
  openshift/release/generate-kafka.sh
  openshift/release/knative-eventing-kafka-sources-v0.6.0.yaml
Labels: approved, lgtm, size/L

#63 Updating the location of the relocated Kafka Source
  Makefile
  openshift/release/resolve.sh
Labels: approved, lgtm, size/XS

#64 Update generate-ci-config.sh base image and upstream to eventing-contrib
  openshift/ci-operator/generate-ci-config.sh
Labels: lgtm, size/XS

#66 Add github adapter/controller to be built
  Makefile
Labels: size/XS

#65 Update OWNERS and ALIASES for repo change
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, size/M

#67 Resolve sh add GitHub
  openshift/release/resolve.sh
Labels: size/XS

#68 GitHub receive adapter fix
  Makefile
  openshift/ci-operator/knative-images/github-receive-adapter/Dockerfile
  openshift/ci-operator/knative-images/github-source-controller/Dockerfile
Labels: lgtm, size/S

#69 Upstream has changed camel's binary location, follow suit
  Makefile
  openshift/release/resolve.sh
Labels: approved, lgtm, size/XS

#72 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#78 Script generate-{release,kafka} make targets in create-release-branch
  openshift/release/create-release-branch.sh
Labels: approved, lgtm, size/XS

#80 Trigger ci on release-v0.7.0 branch
  ci
Labels: approved, lgtm, size/XS
