Repository openshift/knative-eventing-contrib, pull requests merged in 2019-05, with the labels that each got.

#21 Updates to master of latest next release branch files
  Makefile
  OWNERS_ALIASES
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/knative-images/camel-source-controller/Dockerfile
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/kafka-source-adapter/Dockerfile
  openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
  openshift/ci-operator/knative-test-images/k8sevents/Dockerfile
  openshift/release/generate-kafka.sh
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
  openshift/release/update-to-head.sh
Labels: approved, size/L

#24 Delete moved/unsupported image
  openshift/ci-operator/knative-images/awssqs_receive_adapter/Dockerfile
Labels: approved, lgtm, size/XS

#26 update to catch up w/ latest master
  openshift/ci-operator/knative-images/kuberneteseventsource/Dockerfile
Labels: approved, lgtm, size/XS

#31 CI was here
  ci
Labels: approved, lgtm, size/XS

#34 Update script to fail fast and use the repo name in the hub command
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/XS

#36 Camel k port from master
  Gopkg.lock
  Gopkg.toml
  contrib/camel/cmd/controller/main.go
  contrib/camel/config/201-clusterrole.yaml
  contrib/camel/config/300-camelsource.yaml
  contrib/camel/pkg/apis/sources/v1alpha1/camelsource_types.go
  contrib/camel/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  contrib/camel/pkg/install/install.go
  contrib/camel/pkg/reconciler/camelsource.go
  contrib/camel/pkg/reconciler/camelsource_test.go
  contrib/camel/pkg/reconciler/resources/arguments.go
  contrib/camel/pkg/reconciler/resources/component.go
  contrib/camel/pkg/reconciler/resources/integration.go
  contrib/camel/pkg/reconciler/resources/integration_test.go
  contrib/camel/pkg/reconciler/resources/platform.go
  contrib/camel/pkg/reconciler/resources/source.go
  contrib/camel/samples/README.md
  contrib/camel/samples/source_camel_k.yaml
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/build_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/camelcatalog_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/camelcatalog_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/common_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/common_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integration_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integration_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationcontext_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationcontext_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationplatform_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationplatform_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/knative/types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/zz_generated.defaults.go
  vendor/github.com/apache/camel-k/pkg/util/util.go
  vendor/github.com/magiconair/properties/LICENSE
  vendor/github.com/magiconair/properties/decode.go
  vendor/github.com/magiconair/properties/doc.go
  vendor/github.com/magiconair/properties/integrate.go
  vendor/github.com/magiconair/properties/lex.go
  vendor/github.com/magiconair/properties/load.go
  vendor/github.com/magiconair/properties/parser.go
  vendor/github.com/magiconair/properties/properties.go
  vendor/github.com/magiconair/properties/rangecheck.go
Labels: approved, lgtm, size/XXL

#49 Adding sources fork release w/ quay.io images
  openshift/release/knative-eventing-sources-v0.6.0.yaml
Labels: approved, lgtm, size/XL
