Repository openshift/knative-eventing-contrib, pull requests merged in 2019-11, with the labels that each got.

#221 Bug revise of MutatingWebhookName mismatching
  kafka/channel/cmd/webhook/main.go
Labels: approved, lgtm, size/XS

#227 fixing incorrectly generated metrics domain vals
  openshift/release/knative-eventing-kafka-contrib-v0.10.0.yaml
Labels: approved, size/XS

#237 Backport usage of Destination in CamelSource (#700) to release-0.10 b…
  Gopkg.lock
  camel/source/pkg/apis/sources/v1alpha1/camelsource_types.go
  camel/source/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  camel/source/pkg/reconciler/camelsource.go
  camel/source/pkg/reconciler/camelsource_test.go
  camel/source/pkg/reconciler/resources/arguments.go
  camel/source/pkg/reconciler/resources/integration.go
  camel/source/pkg/reconciler/resources/integration_test.go
  camel/source/samples/camel_source_hello_world.yaml
  couchdb/source/pkg/apis/sources/v1alpha1/couchdbsource_lifecycle.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_lifecycle.go
Labels: approved, lgtm, ok-to-test, size/L
