Repository openshift/knative-eventing-contrib, pull requests merged in 2019-10, with the labels that each got.

#175 Adding NetworkPolicy workaround for webhook
  openshift/release/knative-eventing-kafka-contrib-v0.8.2.yaml
Labels: approved, lgtm, size/S

#194 Bump YAML library to latest release :passport_control:
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
Labels: approved, lgtm, size/M

#190 More release doc, clean up dead code.
  Makefile
  README.md
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/release/README.md
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/L

#204 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#203 More release automation
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/ci-operator/update-ci.sh
  openshift/release/README.md
Labels: approved, lgtm, size/L

#200 More release automation
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/ci-operator/update-ci.sh
  openshift/release/README.md
Labels: approved, lgtm, size/L

#208 Correcting scropts to produce correct image names
  openshift/release/generate-camel.sh
  openshift/release/generate-kafka.sh
  openshift/release/resolve.sh
Labels: approved, lgtm, size/S

#207 Fix camel kafka image names
  openshift/release/generate-camel.sh
  openshift/release/generate-kafka.sh
  openshift/release/knative-eventing-camel-sources-v0.9.0.yaml
  openshift/release/knative-eventing-kafka-contrib-v0.9.0.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm, size/S

#212 Adding NetworkPolicy workaround for webhook
  openshift/release/knative-eventing-kafka-contrib-v0.9.0.yaml
Labels: approved, lgtm, size/S
