Repository openshift/knative-eventing-contrib, pull requests merged in 2020-01, with the labels that each got.

#281 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#265 Backport Fix for #805: add duck.InformerFactory to camel source context
  camel/source/pkg/reconciler/camelsource.go
Labels: approved, lgtm, ok-to-test, size/XS

#289 :robot: CI was here...:fire:
  ci
Labels: approved, lgtm, size/XS

#291 Fixing broken METRICS_DOMAIN
  openshift/release/knative-eventing-kafka-contrib-v0.11.2.yaml
Labels: approved, lgtm, size/XS

#293 Adding generator for 4.4 OCP
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm, size/XS

#295 applying defaults for empty flieds
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
Labels: approved, lgtm, size/XS

#304 :robot: CI was here...:fire:
  ci
Labels: approved, lgtm, size/XS

#305 Adjusting new team
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
