Repository openshift/knative-eventing-contrib, pull requests merged in 2020-09, with the labels that each got.

#532 Updating kafka release script
  openshift/release/generate-kafka.sh
Labels: approved, lgtm

#533 Adding Kafka components deploy for Knative
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#535 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#536 Ci updates
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#537 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#539 [0.17] Adding sed fu
  openshift/e2e-common.sh
Labels: approved, lgtm

#540 [master] Adding sed fu
  openshift/e2e-common.sh
Labels: approved, lgtm

#542 Using 1.9 branch of our product
  openshift/e2e-common.sh
Labels: approved, lgtm

#545 Using latest product for nightly
  openshift/e2e-common.sh
Labels: approved, lgtm

#543 Backport SRVKE-467
  couchdb/source/pkg/reconciler/couchdbsource.go
  github/pkg/mtadapter/githubsource_test.go
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_it_test.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  kafka/channel/pkg/reconciler/controller/controller.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/utils/util.go
  kafka/channel/pkg/utils/util_test.go
  kafka/common/pkg/kafka/consumer_factory.go
  kafka/common/pkg/kafka/consumer_factory_test.go
  kafka/common/pkg/kafka/consumer_handler.go
  kafka/common/pkg/kafka/consumer_handler_test.go
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_benchmark_test.go
  kafka/source/pkg/adapter/adapter_test.go
  kafka/source/pkg/adapter/message.go
  natss/pkg/reconciler/dispatcher/natsschannel.go
Labels: approved, area/Couchdb, area/GitHub, area/Kafka, area/NATSS, lgtm

#547 Removing Camel run from nightly, since it was relocated
  Makefile
Labels: approved, lgtm

#549 Backport: 0.17: Use webhook.PortFromEnv
  kafka/channel/cmd/webhook/main.go
Labels: approved, area/Kafka, lgtm

#555 Manually picking slinky's patch to fix CI mess
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go
Labels: approved, area/Kafka, lgtm

#557 Drop github Source
  Makefile
  openshift/ci-operator/knative-images/github-receive-adapter/Dockerfile
  openshift/ci-operator/knative-images/github-source-controller/Dockerfile
  openshift/release/resolve.sh
Labels: approved, lgtm

#548 Adding e2e tests 0.17
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
  openshift/serverless.bash
  test/e2e/camel_source_test.go
Labels: approved, area/test-and-release, lgtm

#564 Release adjustments
  openshift/release/generate-kafka.sh
  openshift/release/knative-eventing-kafka-contrib-v0.17.1.yaml
Labels: approved, lgtm

#567 Rename file to be the CI file...
  openshift/e2e-common.sh
  openshift/release/generate-kafka.sh
  openshift/release/knative-eventing-kafka-contrib-ci.yaml
Labels: approved, lgtm

#569 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#572 Updating to more recent eventing lib
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_redelivery_helper.go
  vendor/modules.txt
Labels: approved, lgtm
