Repository openshift/knative-eventing-contrib, pull requests merged in 2020-08, with the labels that each got.

#495 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#502 Adding httpd-tools
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#501 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#423 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm, needs-ok-to-test

#510 Adding CRD install label first, to avoid race
  openshift/e2e-common.sh
Labels: approved
