Repository openshift/knative-eventing-contrib, pull requests merged in 2020-06, with the labels that each got.

#432 Use Golang 1.14 on container builds
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#439 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#456 Rename user abd4lla to devguyio due to username rename
  OWNERS_ALIASES
Labels: approved, lgtm, needs-ok-to-test
