Repository openshift/knative-eventing-contrib, pull requests merged in 2020-03, with the labels that each got.

#343 Removing myself from eventing contrib and sources approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#346 Backport: upgrade Camel K to 1.0.0-RC2 (#991)
  Gopkg.lock
  Gopkg.toml
  camel/source/pkg/reconciler/camelsource_test.go
  camel/source/pkg/reconciler/resources/integration.go
  camel/source/pkg/reconciler/resources/integration_test.go
  test/config/100-camel-k-1.0.0-RC2.yaml
  test/e2e-tests.sh
  test/e2e/camel_source_test.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/build_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/build_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/camelcatalog_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/camelcatalog_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/common_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integration_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integration_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationkit_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationkit_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationplatform_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationplatform_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/zz_generated.deepcopy.go
Labels: approved, area/test-and-release, lgtm, ok-to-test, size/L

#347 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#358 CI was here...:fire:
  ci
Labels: approved, lgtm

#359 Adding Openshift 4.5 runs
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#363 Porting 0.13.2 resolver fix to master
  openshift/release/resolve.sh
Labels: approved, lgtm

#362 update resolver script, and fix the broken metric_domains
  openshift/release/knative-eventing-kafka-contrib-v0.13.2.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm

#371 tmp fix for incorrect version
  kafka/channel/pkg/dispatcher/dispatcher.go
Labels: approved, area/Kafka, lgtm
