Repository openshift/knative-eventing-contrib, pull requests merged in 2020-12, with the labels that each got.

#640 Use vendor'ed Strimzi
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#641 Close the Body
  kafka/source/pkg/adapter/adapter.go
Labels: approved, area/Kafka, lgtm

#646 Port of https://github.com/knative-sandbox/eventing-kafka/pull/182
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/pkg/kafka/admin.go
  kafka/channel/pkg/kafka/admin_test.go
  kafka/channel/pkg/reconciler/controller/consumer_group_watcher.go
  kafka/channel/pkg/reconciler/controller/consumer_group_watcher_test.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/reconciler/testing/kafkachannel.go
Labels: approved, area/Kafka, lgtm

#642 fix label consistency (#1671)
  kafka/source/pkg/reconciler/source/resources/labels.go
  kafka/source/pkg/reconciler/source/resources/labels_test.go
  test/e2e/helpers/kafka_helper.go
Labels: approved, area/Kafka, area/test-and-release, lgtm

#643 using returns for failed functions
  openshift/e2e-common.sh
Labels: approved, lgtm

#645 Creating TLS/SASL secrets
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved

#644 Adding CI config for 4.7 and new template layout
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#649 [0.18] Backport of https://github.com/knative/eventing-contrib/pull/1670
  kafka/client.go
  kafka/client_test.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_lifecycle.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_lifecycle_test.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_types.go
  kafka/source/pkg/apis/bindings/v1alpha1/zz_generated.deepcopy.go
  kafka/source/pkg/apis/bindings/v1beta1/kafka_lifecycle.go
  kafka/source/pkg/apis/bindings/v1beta1/kafka_lifecycle_test.go
  kafka/source/pkg/apis/bindings/v1beta1/kafka_types.go
  kafka/source/pkg/apis/bindings/v1beta1/zz_generated.deepcopy.go
  kafka/source/pkg/reconciler/source/resources/receive_adapter.go
  kafka/source/pkg/reconciler/source/resources/receive_adapter_test.go
  openshift/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/kafka_binding_test.go
  test/e2e/kafka_source_reconciler_test.go
  test/e2e/kafka_source_test.go
Labels: approved, area/Kafka, area/test-and-release, lgtm

#650 Use our own Eventing 0.18.6 images for install
  openshift/e2e-common.sh
Labels: approved, lgtm

#651 Moving the secret creation inside the test runner...
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#652 Improvements
  kafka/channel/config/roles/dispatcher-clusterrole.yaml
  kafka/channel/pkg/kafka/admin.go
Labels: approved, area/Kafka, lgtm

#653 Regenerate yamls
  openshift/release/knative-eventing-kafka-channel-ci.yaml
Labels: approved, lgtm

#654 fix custom consumer group error channel lifecycle (#263)
  kafka/common/pkg/kafka/consumer_factory.go
  kafka/common/pkg/kafka/consumer_factory_test.go
  kafka/common/pkg/kafka/consumer_handler.go
  kafka/common/pkg/kafka/consumer_handler_test.go
Labels: approved, area/Kafka, lgtm, ok-to-test

#648 TLS/SASL e2e runs
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
  openshift/release/knative-eventing-kafka-channel-sasl-ci.yaml
  openshift/release/knative-eventing-kafka-channel-tls-ci.yaml
  openshift/release/knative-eventing-kafka-source-ci.yaml
Labels: approved, lgtm

#655 Using latest of product
  openshift/e2e-common.sh
Labels: approved, lgtm

#656 No auto create of topics
  test/config/100-kafka-ephemeral-triple-2.6.0.yaml
Labels: approved, area/test-and-release, lgtm

#657 Backporting 273 from upstream
  kafka/source/pkg/adapter/adapter.go
Labels: approved, area/Kafka, lgtm
