Repository openshift/knative-eventing-contrib, pull requests merged in 2020-02, with the labels that each got.

#314 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#318 do not prefix extension headers with ce (#905) (#907)
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, lgtm, size/XS

#322 updatding image
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, size/XS

#328 not forcing a specific version
  kafka/channel/pkg/dispatcher/dispatcher.go
Labels: approved, area/Kafka, lgtm, size/XS

#334 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS
