Repository openshift/knative-eventing-contrib, pull requests merged in 2020-10, with the labels that each got.

#571 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#573 No `header_text` bash function is available
  openshift/e2e-common.sh
Labels: approved, lgtm

#575 [0.18] Port https://github.com/knative/eventing-contrib/pull/1630 here
  kafka/channel/config/deployments/webhook.yaml
  kafka/source/config/deployments/controller.yaml
Labels: approved, area/Kafka, lgtm

#582 Fix openshift 017 build
  openshift/e2e-common.sh
Labels: approved, lgtm

#581 CI was here...:fire:
  ci
Labels: approved

#583 Update to release yaml
  openshift/release/knative-eventing-kafka-contrib-ci.yaml
Labels: approved, lgtm

#584 Updateing release yam
  openshift/release/knative-eventing-kafka-contrib-v0.18.0.yaml
Labels: approved, lgtm

#586 [0.18] Backport https://github.com/knative-sandbox/eventing-kafka/pull/96
  kafka/channel/config/deployments/dispatcher.yaml
  kafka/source/config/configmaps/observability.yaml
  kafka/source/config/roles/clusterrole.yaml
  kafka/source/config/webhooks/kafka.yaml
  openshift/release/knative-eventing-kafka-contrib-v0.18.0.yaml
Labels: approved, area/Kafka, lgtm

#585 [0.17] Backport https://github.com/knative-sandbox/eventing-kafka/pull/96
  kafka/channel/config/500-dispatcher.yaml
  kafka/source/config/201-clusterrole.yaml
  kafka/source/config/500-webhook-configuration.yaml
  kafka/source/config/config-observability.yaml
  openshift/release/knative-eventing-camel-sources-v0.17.1.yaml
  openshift/release/knative-eventing-kafka-contrib-ci.yaml
Labels: approved, area/Kafka, lgtm

#587 Set dispatcher replica to 1
  kafka/channel/config/500-dispatcher.yaml
  openshift/release/knative-eventing-kafka-contrib-ci.yaml
Labels: approved, area/Kafka, lgtm

#588 Strimzi updates and wait for deployment
  openshift/e2e-common.sh
Labels: approved

#593 [0.18] adding yq to the build
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#594 [0.17] adding yq to the build
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#597 Reduce the parallel to avoid timeouts
  openshift/e2e-common.sh
Labels: approved, lgtm

#599 Skipping potential flake
  test/e2e/broker_redelivery_test.go
Labels: approved, area/test-and-release, lgtm

#601 [0.17] Removed alpha tests
  openshift/e2e-common.sh
Labels: approved, lgtm

#600 [0.17] Updating the product base to 1.10 release
  openshift/e2e-common.sh
  openshift/serverless.bash
Labels: approved, lgtm

#606 [0.18] Oc wait for strimzi crds
  openshift/e2e-common.sh
Labels: approved, lgtm

#607 [0.17] oc wait for strimzi crds
  openshift/e2e-common.sh
Labels: approved, lgtm

#605 run redelivery
  test/e2e/broker_redelivery_test.go
Labels: approved, area/test-and-release, lgtm

#610 [0.17] Backport https://github.com/knative/pkg/pull/1842
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/modules.txt
Labels: approved, lgtm

#608 Running e2e and base on 1.10
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
  openshift/release/knative-eventing-kafka-contrib-ci.yaml
  openshift/serverless.bash
Labels: approved, lgtm

#611 Fix KafkaSource conversion (#1650)
  kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion_test.go
Labels: approved, area/Kafka, lgtm

#612 Fix KafkaBinding conversion (#1651)
  kafka/source/config/300-kafkabinding.yaml
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
Labels: approved, area/Kafka, lgtm

#613 Openshift 018 fix kafkabinding conversion
  kafka/source/config/resources/kafkabinding.yaml
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
Labels: approved, area/Kafka, area/test-and-release, lgtm

#614 Update to latest upstream eventing 0.17 deps
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/dropevents/receiver.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/logger_vent/logger.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/modules.txt
Labels: approved, lgtm

#615 [0.17] Updates to latest
  go.mod
  go.sum
  test/e2e/broker_channel_flow_test.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, area/test-and-release, lgtm

#616 [0.18] Updates to latest
  go.mod
  go.sum
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, area/Kafka, lgtm

#617 [0.17] Enabling tracing and bump parallel
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#619 Going back to parallel of 12
  openshift/e2e-common.sh
  test/e2e/broker_event_transformation_test.go
Labels: approved, area/test-and-release, lgtm
