Repository openshift/knative-eventing-contrib, pull requests merged in 2020-11, with the labels that each got.

#620 Update Kafka release YAML
  openshift/release/knative-eventing-kafka-contrib-ci.yaml
Labels: approved, lgtm

#623 [0.18] Wait until Kafka CR is ready
  openshift/e2e-common.sh
Labels: approved, lgtm

#622 [0.17] Wait until Kafka CR is ready
  openshift/e2e-common.sh
Labels: approved, lgtm

#621 Update Kafka release YAML
  openshift/release/knative-eventing-kafka-contrib-ci.yaml
Labels: approved, lgtm

#624 Updating to latest
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, lgtm

#625 Backport https://github.com/knative/eventing-contrib/pull/1660
  kafka/channel/config/deployments/dispatcher.yaml
Labels: approved, area/Kafka, lgtm

#626 Adding test images to our CI build
  Makefile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/filterevents/Dockerfile
  openshift/ci-operator/knative-test-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-test-images/performance/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/sequencestepper/Dockerfile
  openshift/ci-operator/knative-test-images/transformevents/Dockerfile
Labels: approved, lgtm

#627 Aliging script to wat we have for eventing core
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#628 disable leader election (#173) (#1663)
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/config/roles/dispatcher-clusterrole.yaml
Labels: approved, area/Kafka, lgtm

#629 Setting default zap logger to 'info'
  kafka/source/config/configmaps/observability.yaml
Labels: approved, area/Kafka, lgtm

#632 unset OPENSHIFT_CI
  openshift/e2e-common.sh
Labels: approved, lgtm

#633 unset OPENSHIFT_CI
  openshift/e2e-common.sh
Labels: approved, lgtm

#631 Better release yamls
  kafka/source/config/config-leader-election.yaml
  kafka/source/config/config-observability.yaml
  openshift/e2e-common.sh
  openshift/patches/001-remove-config-symlinks.patch
  openshift/release/create-release-branch.sh
  openshift/release/generate-kafka.sh
  openshift/release/knative-eventing-kafka-channel-ci.yaml
  openshift/release/knative-eventing-kafka-source-ci.yaml
  openshift/release/resolve.sh
Labels: approved, area/Kafka, lgtm

#635 [0.18] don't use session context to send messages (#179) (#1664)
  kafka/common/pkg/kafka/consumer_handler.go
Labels: approved, area/Kafka, lgtm

#636 Backport auth kafkachannel
  go.mod
  go.sum
  kafka/channel/config/configmaps/kafka-config.yaml
  kafka/channel/config/roles/controller-clusterrole.yaml
  kafka/channel/config/roles/dispatcher-clusterrole.yaml
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/utils/util.go
  kafka/channel/pkg/utils/util_test.go
  kafka/client.go
  kafka/client_test.go
  kafka/kafka_scram_client.go
  openshift/e2e-common.sh
  test/config/100-kafka-ephemeral-triple-2.5.0.yaml
  test/config/100-kafka-ephemeral-triple-2.6.0.yaml
  test/config/100-strimzi-cluster-operator-0.20.0.yaml
  test/config/100-strimzi-users-0.20.0.yaml
  test/config/config-kafka-sasl.yaml
  test/config/config-kafka-tls.yaml
  test/e2e-tests.sh
  test/e2e/kafka_binding_test.go
  test/e2e/kafka_source_reconciler_test.go
  test/e2e/kafka_source_test.go
  third_party/VENDOR-LICENSE/github.com/xdg/scram/LICENSE
  third_party/VENDOR-LICENSE/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/scram/.gitignore
  vendor/github.com/xdg/scram/.travis.yml
  vendor/github.com/xdg/scram/LICENSE
  vendor/github.com/xdg/scram/README.md
  vendor/github.com/xdg/scram/client.go
  vendor/github.com/xdg/scram/client_conv.go
  vendor/github.com/xdg/scram/common.go
  vendor/github.com/xdg/scram/doc.go
  vendor/github.com/xdg/scram/parse.go
  vendor/github.com/xdg/scram/scram.go
  vendor/github.com/xdg/scram/server.go
  vendor/github.com/xdg/scram/server_conv.go
  vendor/github.com/xdg/stringprep/.gitignore
  vendor/github.com/xdg/stringprep/.travis.yml
  vendor/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/stringprep/README.md
  vendor/github.com/xdg/stringprep/bidi.go
  vendor/github.com/xdg/stringprep/doc.go
  vendor/github.com/xdg/stringprep/error.go
  vendor/github.com/xdg/stringprep/map.go
  vendor/github.com/xdg/stringprep/profile.go
  vendor/github.com/xdg/stringprep/saslprep.go
  vendor/github.com/xdg/stringprep/set.go
  vendor/github.com/xdg/stringprep/tables.go
  vendor/modules.txt
Labels: approved, area/Kafka, area/test-and-release, lgtm

#637 Updating the generated yamls
  openshift/release/generate-kafka.sh
  openshift/release/knative-eventing-kafka-channel-ci.yaml
  openshift/release/knative-eventing-kafka-source-ci.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm

#638 Adding more in bash
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm
